import type { INodeProperties } from 'n8n-workflow';

export const dubbingDescription: INodeProperties[] = [
	{
		displayName: 'Input Type',
		name: 'inputType',
		type: 'options',
		required: true,
		default: 'file',
		options: [
			{
				name: 'File',
				value: 'file',
				description: 'Upload an file that you want to dub',
			},
			{
				name: 'URL',
				value: 'url',
				description: 'Use a publicly accessible file URL',
			},
		],
		description: 'Whether to upload a file or use a URL',
	},
	{
		displayName: 'File',
		name: 'file',
		type: 'string',
		default: 'data',
		displayOptions: {
			show: {
				inputType: ['file'],
			},
		},
		description: 'The audio/video file to dub. All major audio and video formats are supported.',
	},
	{
		displayName: 'File URL',
		name: 'fileUrl',
		type: 'string',
		displayOptions: {
			show: {
				inputType: ['url'],
			},
		},
		default: '',
		placeholder: 'https://example.com/video.mp4',
		description: 'URL of the audio/video file to be dubbed (must be publicly accessible)',
	},
	{
		displayName: 'File Name',
		name: 'fileName',
		type: 'string',
		default: '',
		placeholder: 'my-video.mp4',
		description: 'Name of the file for reference',
	},
	{
		displayName: 'Target Languages',
		name: 'targetLocales',
		type: 'multiOptions',
		required: true,
		options: [
			{ name: 'Bengali', value: 'bn_IN' },
			{ name: 'Danish', value: 'da_DK' },
			{ name: 'Dutch', value: 'nl_NL' },
			{ name: 'English (Australia)', value: 'en_AU' },
			{ name: 'English (India)', value: 'en_IN' },
			{ name: 'English (Scotland)', value: 'en_SCOTT' },
			{ name: 'English (UK)', value: 'en_UK' },
			{ name: 'English (US & Canada)', value: 'en_US' },
			{ name: 'Finnish', value: 'fi_FI' },
			{ name: 'French', value: 'fr_FR' },
			{ name: 'German', value: 'de_DE' },
			{ name: 'Hindi', value: 'hi_IN' },
			{ name: 'Indonesian', value: 'id_ID' },
			{ name: 'Italian', value: 'it_IT' },
			{ name: 'Japanese', value: 'ja_JP' },
			{ name: 'Korean', value: 'ko_KR' },
			{ name: 'Mandarin (Chinese)', value: 'zh_CN' },
			{ name: 'Norwegian', value: 'nb_NO' },
			{ name: 'Polish', value: 'pl_PL' },
			{ name: 'Portuguese (Brazil)', value: 'pt_BR' },
			{ name: 'Romanian', value: 'ro_RO' },
			{ name: 'Russian', value: 'ru_RU' },
			{ name: 'Spanish (Mexico)', value: 'es_MX' },
			{ name: 'Spanish (Spain)', value: 'es_ES' },
			{ name: 'Tamil', value: 'ta_IN' },
			{ name: 'Turkish', value: 'tr_TR' },
			{ name: 'Ukrainian', value: 'uk_UA' },
		],
		default: ['en_US'],
		description: 'Languages to dub the content into',
	},
	{
		displayName: 'Priority',
		name: 'priority',
		type: 'options',
		options: [
			{
				name: 'Low',
				value: 'LOW',
				description: 'Lower priority processing',
			},
			{
				name: 'High',
				value: 'HIGH',
				description: 'Higher priority processing (may incur additional cost)',
			},
		],
		default: 'LOW',
		description: 'Processing priority for the dubbing job',
	},
	{
		displayName: 'Webhook URL',
		name: 'webhookUrl',
		type: 'string',
		default: '',
		description: 'URL to receive webhook notifications on job status changes (optional)',
	},
	{
		displayName: 'Webhook Secret',
		name: 'webhookSecret',
		type: 'string',
		typeOptions: {
			password: true,
		},
		displayOptions: {
			show: {
				webhookUrl: ['', false],
			},
		},
		default: '',
		description: 'Secret to validate webhook authenticity (optional)',
	},
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		options: [
			{
				displayName: 'Create Project',
				name: 'createProject',
				type: 'boolean',
				default: false,
				description: 'Whether to create a persistent project (allows editing in Murf UI)',
			},
			{
				displayName: 'Project ID',
				name: 'projectId',
				type: 'string',
				default: '',
				description: 'ID of the project to associate with this dubbing job',
			},
		],
	},
];
